name: backend-cicd
on:
  push:
  workflow_dispatch:
jobs:
  common:
    uses: linga-devsecops-actions/14.12.github-actions-expense-reusable-workflows/.github/workflows/nodejs-common.yaml@main
    with:
      project: expense
      component: backend
      environment: dev
      app_type: nodejs
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
